[[ontologies]]
shortname = "roh"
uri_base = "http://w3id.org/roh#"

[[ontologies]]
shortname = "rohes"
uri_base = "http://w3id.org/rohes#"

[[ontologies]]
shortname = "bibo"
uri_base = "http://w3id.org/roh/mirror/bibo#"

[[ontologies]]
shortname = "vivo"
uri_base = "http://w3id.org/roh/mirror/vivo#"

[[ontologies]]
shortname = "foaf"
uri_base = "http://w3id.org/roh/mirror/foaf#"

[[ontologies]]
shortname = "ro"
uri_base = "http://w3id.org/roh/mirror/obo/ro#"

[[ontologies]]
shortname = "bfo"
uri_base = "http://w3id.org/roh/mirror/obo/bfo#"

[[ontologies]]
shortname= "iao"
uri_base= "http://w3id.org/roh/mirror/obo/iao#"


[[ontologies]]
shortname = "owl"
uri_base = "http://www.w3.org/2002/07/owl#"

[[ontologies]]
shortname = "vcard"
uri_base = "http://w3id.org/roh/mirror/vcard#"

[[ontologies]]
shortname = "xsd"
uri_base = "http://www.w3.org/2001/XMLSchema#"

[[ontologies]]
shortname = "rdf"
uri_base = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"

[[ontologies]]
shortname = "rdfs"
uri_base = "http://www.w3.org/2000/01/rdf-schema#"

[[ontologies]]
shortname = "gn"
uri_base = "http://w3id.org/roh/mirror/geonames#"
