//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ServiceModel;

namespace Import
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.cvnet.fecyt.es", ConfigurationName="Import.Cvn2RootBean")]
    public interface Cvn2RootBean
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cvnet.fecyt.es/Cvn2RootBean/cvnPdf2XmlRequest", ReplyAction="http://ws.cvnet.fecyt.es/Cvn2RootBean/cvnPdf2XmlResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CvnBean))]
        System.Threading.Tasks.Task<Import.cvnPdf2XmlResponse> cvnPdf2XmlAsync(Import.cvnPdf2XmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cvnet.fecyt.es/Cvn2RootBean/cvnPdf2CvnRootBeanRequest", ReplyAction="http://ws.cvnet.fecyt.es/Cvn2RootBean/cvnPdf2CvnRootBeanResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CvnBean))]
        System.Threading.Tasks.Task<Import.cvnPdf2CvnRootBeanResponse> cvnPdf2CvnRootBeanAsync(Import.cvnPdf2CvnRootBeanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cvnet.fecyt.es/Cvn2RootBean/cvnXml2XmlRequest", ReplyAction="http://ws.cvnet.fecyt.es/Cvn2RootBean/cvnXml2XmlResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CvnBean))]
        System.Threading.Tasks.Task<Import.cvnXml2XmlResponse> cvnXml2XmlAsync(Import.cvnXml2XmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.cvnet.fecyt.es/Cvn2RootBean/cvnXml2CvnRootBeanRequest", ReplyAction="http://ws.cvnet.fecyt.es/Cvn2RootBean/cvnXml2CvnRootBeanResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CvnBean))]
        System.Threading.Tasks.Task<Import.cvnXml2CvnRootBeanResponse> cvnXml2CvnRootBeanAsync(Import.cvnXml2CvnRootBeanRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cvnet.fecyt.es")]
    public partial class cvnXmlResultBean
    {
        
        private byte[] cvnXmlField;
        
        private int errorCodeField;
        
        private bool errorCodeFieldSpecified;
        
        private string errorMessageField;
        
        private int numElementosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] cvnXml
        {
            get
            {
                return this.cvnXmlField;
            }
            set
            {
                this.cvnXmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorCodeSpecified
        {
            get
            {
                return this.errorCodeFieldSpecified;
            }
            set
            {
                this.errorCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int numElementos
        {
            get
            {
                return this.numElementosField;
            }
            set
            {
                this.numElementosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnVolumeBean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnTitleBean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnString))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnRichText))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnPhotoBean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnPhoneBean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnPageBean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnExternalPKBean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnEntityBean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnDuration))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnDouble))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnDateYear))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnDateMonthYear))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnDateDayMonthYear))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnBoolean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnFamilyNameBean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnAuthorBean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnItemBean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnCodeGroup))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnBean
    {
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnVolumeBean : CvnBean
    {
        
        private string numberField;
        
        private string volumeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Volume
        {
            get
            {
                return this.volumeField;
            }
            set
            {
                this.volumeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnTitleBean : CvnBean
    {
        
        private string identificationField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Identification
        {
            get
            {
                return this.identificationField;
            }
            set
            {
                this.identificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnRichText))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnString : CvnBean
    {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnRichText : CvnString
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnPhotoBean : CvnBean
    {
        
        private string bytesInBase64Field;
        
        private string mimeTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BytesInBase64
        {
            get
            {
                return this.bytesInBase64Field;
            }
            set
            {
                this.bytesInBase64Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnPhoneBean : CvnBean
    {
        
        private string extensionField;
        
        private string internationalCodeField;
        
        private string numberField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InternationalCode
        {
            get
            {
                return this.internationalCodeField;
            }
            set
            {
                this.internationalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnPageBean : CvnBean
    {
        
        private string finalPageField;
        
        private string initialPageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FinalPage
        {
            get
            {
                return this.finalPageField;
            }
            set
            {
                this.finalPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InitialPage
        {
            get
            {
                return this.initialPageField;
            }
            set
            {
                this.initialPageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnExternalPKBean : CvnBean
    {
        
        private string typeField;
        
        private string valueField;
        
        private string othersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Others
        {
            get
            {
                return this.othersField;
            }
            set
            {
                this.othersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnEntityBean : CvnBean
    {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnDuration : CvnBean
    {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnDouble : CvnBean
    {
        
        private double valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified
        {
            get
            {
                return this.valueFieldSpecified;
            }
            set
            {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnDateYear : CvnBean
    {
        
        private System.DateTime valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified
        {
            get
            {
                return this.valueFieldSpecified;
            }
            set
            {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnDateMonthYear : CvnBean
    {
        
        private System.DateTime valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified
        {
            get
            {
                return this.valueFieldSpecified;
            }
            set
            {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnDateDayMonthYear : CvnBean
    {
        
        private System.DateTime valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified
        {
            get
            {
                return this.valueFieldSpecified;
            }
            set
            {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnBoolean : CvnBean
    {
        
        private bool valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified
        {
            get
            {
                return this.valueFieldSpecified;
            }
            set
            {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnFamilyNameBean : CvnBean
    {
        
        private string firstFamilyNameField;
        
        private string secondFamilyNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FirstFamilyName
        {
            get
            {
                return this.firstFamilyNameField;
            }
            set
            {
                this.firstFamilyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SecondFamilyName
        {
            get
            {
                return this.secondFamilyNameField;
            }
            set
            {
                this.secondFamilyNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnAuthorBean : CvnBean
    {
        
        private CvnFamilyNameBean cvnFamilyNameBeanField;
        
        private string givenNameField;
        
        private string signatureField;
        
        private int signatureOrderField;
        
        private bool signatureOrderFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CvnFamilyNameBean CvnFamilyNameBean
        {
            get
            {
                return this.cvnFamilyNameBeanField;
            }
            set
            {
                this.cvnFamilyNameBeanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GivenName
        {
            get
            {
                return this.givenNameField;
            }
            set
            {
                this.givenNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SignatureOrder
        {
            get
            {
                return this.signatureOrderField;
            }
            set
            {
                this.signatureOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SignatureOrderSpecified
        {
            get
            {
                return this.signatureOrderFieldSpecified;
            }
            set
            {
                this.signatureOrderFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CvnCodeGroup))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnItemBean : CvnBean
    {
        
        private CvnAuthorBean[] cvnAuthorBeanField;
        
        private CvnBoolean[] cvnBooleanField;
        
        private CvnCodeGroup[] cvnCodeGroupField;
        
        private CvnDateDayMonthYear[] cvnDateDayMonthYearField;
        
        private CvnDateMonthYear[] cvnDateMonthYearField;
        
        private CvnDateYear[] cvnDateYearField;
        
        private CvnDouble[] cvnDoubleField;
        
        private CvnDuration[] cvnDurationField;
        
        private CvnEntityBean[] cvnEntityBeanField;
        
        private CvnExternalPKBean[] cvnExternalPKBeanField;
        
        private CvnFamilyNameBean[] cvnFamilyNameBeanField;
        
        private CvnPageBean[] cvnPageBeanField;
        
        private CvnPhoneBean[] cvnPhoneBeanField;
        
        private CvnPhotoBean[] cvnPhotoBeanField;
        
        private CvnRichText[] cvnRichTextField;
        
        private CvnString[] cvnStringField;
        
        private CvnTitleBean[] cvnTitleBeanField;
        
        private CvnVolumeBean[] cvnVolumeBeanField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnAuthorBean", Order=0)]
        public CvnAuthorBean[] CvnAuthorBean
        {
            get
            {
                return this.cvnAuthorBeanField;
            }
            set
            {
                this.cvnAuthorBeanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnBoolean", Order=1)]
        public CvnBoolean[] CvnBoolean
        {
            get
            {
                return this.cvnBooleanField;
            }
            set
            {
                this.cvnBooleanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnCodeGroup", Order=2)]
        public CvnCodeGroup[] CvnCodeGroup
        {
            get
            {
                return this.cvnCodeGroupField;
            }
            set
            {
                this.cvnCodeGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnDateDayMonthYear", Order=3)]
        public CvnDateDayMonthYear[] CvnDateDayMonthYear
        {
            get
            {
                return this.cvnDateDayMonthYearField;
            }
            set
            {
                this.cvnDateDayMonthYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnDateMonthYear", Order=4)]
        public CvnDateMonthYear[] CvnDateMonthYear
        {
            get
            {
                return this.cvnDateMonthYearField;
            }
            set
            {
                this.cvnDateMonthYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnDateYear", Order=5)]
        public CvnDateYear[] CvnDateYear
        {
            get
            {
                return this.cvnDateYearField;
            }
            set
            {
                this.cvnDateYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnDouble", Order=6)]
        public CvnDouble[] CvnDouble
        {
            get
            {
                return this.cvnDoubleField;
            }
            set
            {
                this.cvnDoubleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnDuration", Order=7)]
        public CvnDuration[] CvnDuration
        {
            get
            {
                return this.cvnDurationField;
            }
            set
            {
                this.cvnDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnEntityBean", Order=8)]
        public CvnEntityBean[] CvnEntityBean
        {
            get
            {
                return this.cvnEntityBeanField;
            }
            set
            {
                this.cvnEntityBeanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnExternalPKBean", Order=9)]
        public CvnExternalPKBean[] CvnExternalPKBean
        {
            get
            {
                return this.cvnExternalPKBeanField;
            }
            set
            {
                this.cvnExternalPKBeanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnFamilyNameBean", Order=10)]
        public CvnFamilyNameBean[] CvnFamilyNameBean
        {
            get
            {
                return this.cvnFamilyNameBeanField;
            }
            set
            {
                this.cvnFamilyNameBeanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnPageBean", Order=11)]
        public CvnPageBean[] CvnPageBean
        {
            get
            {
                return this.cvnPageBeanField;
            }
            set
            {
                this.cvnPageBeanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnPhoneBean", Order=12)]
        public CvnPhoneBean[] CvnPhoneBean
        {
            get
            {
                return this.cvnPhoneBeanField;
            }
            set
            {
                this.cvnPhoneBeanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnPhotoBean", Order=13)]
        public CvnPhotoBean[] CvnPhotoBean
        {
            get
            {
                return this.cvnPhotoBeanField;
            }
            set
            {
                this.cvnPhotoBeanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnRichText", Order=14)]
        public CvnRichText[] CvnRichText
        {
            get
            {
                return this.cvnRichTextField;
            }
            set
            {
                this.cvnRichTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnString", Order=15)]
        public CvnString[] CvnString
        {
            get
            {
                return this.cvnStringField;
            }
            set
            {
                this.cvnStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnTitleBean", Order=16)]
        public CvnTitleBean[] CvnTitleBean
        {
            get
            {
                return this.cvnTitleBeanField;
            }
            set
            {
                this.cvnTitleBeanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CvnVolumeBean", Order=17)]
        public CvnVolumeBean[] CvnVolumeBean
        {
            get
            {
                return this.cvnVolumeBeanField;
            }
            set
            {
                this.cvnVolumeBeanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://codes.cvn.fecyt.es/beans")]
    public partial class CvnCodeGroup : CvnItemBean
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cvnet.fecyt.es")]
    public partial class cvnRootResultBean
    {
        
        private CvnItemBean[] cvnRootBeanField;
        
        private int errorCodeField;
        
        private bool errorCodeFieldSpecified;
        
        private string errorMessageField;
        
        private int numElementosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://codes.cvn.fecyt.es/beans", IsNullable=false)]
        public CvnItemBean[] cvnRootBean
        {
            get
            {
                return this.cvnRootBeanField;
            }
            set
            {
                this.cvnRootBeanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorCodeSpecified
        {
            get
            {
                return this.errorCodeFieldSpecified;
            }
            set
            {
                this.errorCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int numElementos
        {
            get
            {
                return this.numElementosField;
            }
            set
            {
                this.numElementosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cvnPdf2Xml", WrapperNamespace="http://ws.cvnet.fecyt.es", IsWrapped=true)]
    public partial class cvnPdf2XmlRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=1)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] pdfBytes;
        
        public cvnPdf2XmlRequest()
        {
        }
        
        public cvnPdf2XmlRequest(string user, string passwd, byte[] pdfBytes)
        {
            this.user = user;
            this.passwd = passwd;
            this.pdfBytes = pdfBytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cvnPdf2XmlResponse", WrapperNamespace="http://ws.cvnet.fecyt.es", IsWrapped=true)]
    public partial class cvnPdf2XmlResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=0)]
        public Import.cvnXmlResultBean @return;
        
        public cvnPdf2XmlResponse()
        {
        }
        
        public cvnPdf2XmlResponse(Import.cvnXmlResultBean @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cvnPdf2CvnRootBean", WrapperNamespace="http://ws.cvnet.fecyt.es", IsWrapped=true)]
    public partial class cvnPdf2CvnRootBeanRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=1)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] pdfBytes;
        
        public cvnPdf2CvnRootBeanRequest()
        {
        }
        
        public cvnPdf2CvnRootBeanRequest(string user, string passwd, byte[] pdfBytes)
        {
            this.user = user;
            this.passwd = passwd;
            this.pdfBytes = pdfBytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cvnPdf2CvnRootBeanResponse", WrapperNamespace="http://ws.cvnet.fecyt.es", IsWrapped=true)]
    public partial class cvnPdf2CvnRootBeanResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=0)]
        public Import.cvnRootResultBean @return;
        
        public cvnPdf2CvnRootBeanResponse()
        {
        }
        
        public cvnPdf2CvnRootBeanResponse(Import.cvnRootResultBean @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cvnXml2Xml", WrapperNamespace="http://ws.cvnet.fecyt.es", IsWrapped=true)]
    public partial class cvnXml2XmlRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=1)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] xmlBytes;
        
        public cvnXml2XmlRequest()
        {
        }
        
        public cvnXml2XmlRequest(string user, string passwd, byte[] xmlBytes)
        {
            this.user = user;
            this.passwd = passwd;
            this.xmlBytes = xmlBytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cvnXml2XmlResponse", WrapperNamespace="http://ws.cvnet.fecyt.es", IsWrapped=true)]
    public partial class cvnXml2XmlResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=0)]
        public Import.cvnXmlResultBean @return;
        
        public cvnXml2XmlResponse()
        {
        }
        
        public cvnXml2XmlResponse(Import.cvnXmlResultBean @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cvnXml2CvnRootBean", WrapperNamespace="http://ws.cvnet.fecyt.es", IsWrapped=true)]
    public partial class cvnXml2CvnRootBeanRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=1)]
        public string passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] xmlBytes;
        
        public cvnXml2CvnRootBeanRequest()
        {
        }
        
        public cvnXml2CvnRootBeanRequest(string user, string passwd, byte[] xmlBytes)
        {
            this.user = user;
            this.passwd = passwd;
            this.xmlBytes = xmlBytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cvnXml2CvnRootBeanResponse", WrapperNamespace="http://ws.cvnet.fecyt.es", IsWrapped=true)]
    public partial class cvnXml2CvnRootBeanResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cvnet.fecyt.es", Order=0)]
        public Import.cvnRootResultBean @return;
        
        public cvnXml2CvnRootBeanResponse()
        {
        }
        
        public cvnXml2CvnRootBeanResponse(Import.cvnRootResultBean @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface Cvn2RootBeanChannel : Import.Cvn2RootBean, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class Cvn2RootBeanClient : System.ServiceModel.ClientBase<Import.Cvn2RootBean>, Import.Cvn2RootBean
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public Cvn2RootBeanClient() :
                base(Cvn2RootBeanClient.GetDefaultBinding(), Cvn2RootBeanClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Cvn2RootBeanPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public Cvn2RootBeanClient(EndpointConfiguration endpointConfiguration) :
                base(Cvn2RootBeanClient.GetBindingForEndpoint(endpointConfiguration), Cvn2RootBeanClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public Cvn2RootBeanClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(Cvn2RootBeanClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public Cvn2RootBeanClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(Cvn2RootBeanClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public Cvn2RootBeanClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Import.cvnPdf2XmlResponse> Import.Cvn2RootBean.cvnPdf2XmlAsync(Import.cvnPdf2XmlRequest request)
        {
            return base.Channel.cvnPdf2XmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<Import.cvnPdf2XmlResponse> cvnPdf2XmlAsync(string user, string passwd, byte[] pdfBytes)
        {
            Import.cvnPdf2XmlRequest inValue = new Import.cvnPdf2XmlRequest();
            inValue.user = user;
            inValue.passwd = passwd;
            inValue.pdfBytes = pdfBytes;
            return ((Import.Cvn2RootBean)(this)).cvnPdf2XmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Import.cvnPdf2CvnRootBeanResponse> Import.Cvn2RootBean.cvnPdf2CvnRootBeanAsync(Import.cvnPdf2CvnRootBeanRequest request)
        {
            return base.Channel.cvnPdf2CvnRootBeanAsync(request);
        }
        
        public System.Threading.Tasks.Task<Import.cvnPdf2CvnRootBeanResponse> cvnPdf2CvnRootBeanAsync(string user, string passwd, byte[] pdfBytes)
        {
            Import.cvnPdf2CvnRootBeanRequest inValue = new Import.cvnPdf2CvnRootBeanRequest();
            inValue.user = user;
            inValue.passwd = passwd;
            inValue.pdfBytes = pdfBytes;
            return ((Import.Cvn2RootBean)(this)).cvnPdf2CvnRootBeanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Import.cvnXml2XmlResponse> Import.Cvn2RootBean.cvnXml2XmlAsync(Import.cvnXml2XmlRequest request)
        {
            return base.Channel.cvnXml2XmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<Import.cvnXml2XmlResponse> cvnXml2XmlAsync(string user, string passwd, byte[] xmlBytes)
        {
            Import.cvnXml2XmlRequest inValue = new Import.cvnXml2XmlRequest();
            inValue.user = user;
            inValue.passwd = passwd;
            inValue.xmlBytes = xmlBytes;
            return ((Import.Cvn2RootBean)(this)).cvnXml2XmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Import.cvnXml2CvnRootBeanResponse> Import.Cvn2RootBean.cvnXml2CvnRootBeanAsync(Import.cvnXml2CvnRootBeanRequest request)
        {
            return base.Channel.cvnXml2CvnRootBeanAsync(request);
        }
        
        public System.Threading.Tasks.Task<Import.cvnXml2CvnRootBeanResponse> cvnXml2CvnRootBeanAsync(string user, string passwd, byte[] xmlBytes)
        {
            Import.cvnXml2CvnRootBeanRequest inValue = new Import.cvnXml2CvnRootBeanRequest();
            inValue.user = user;
            inValue.passwd = passwd;
            inValue.xmlBytes = xmlBytes;
            return ((Import.Cvn2RootBean)(this)).cvnXml2CvnRootBeanAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }


        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Cvn2RootBeanPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Cvn2RootBeanPort))
            {
                return new System.ServiceModel.EndpointAddress("https://integraciones.cvnet.es/cvn2RootBean_v1_4/services/Cvn2RootBean");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Cvn2RootBeanClient.GetBindingForEndpoint(EndpointConfiguration.Cvn2RootBeanPort);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Cvn2RootBeanClient.GetEndpointAddress(EndpointConfiguration.Cvn2RootBeanPort);
        }

        public enum EndpointConfiguration
        {

            Cvn2RootBeanPort,
        }
    }
}
