using API_CARGA.Models.Entities;
using API_CARGA.Models.Services;
using API_CARGA.Models.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml;
using Xunit;

namespace XUnitTestAPI_CARGA
{
    public class UnitTestOperationsEtl
    {
        [Fact]
        public void DataPublish()
        {
            XmlDocument rdfxml = new XmlDocument();
            rdfxml.LoadXml(rdfFile);
            List<string> triples = SparqlUtility.GetTriplesFromRDF(rdfxml);
            SparqlUtility.LoadTriples(triples, "", "", "http://testgraph.com");
            Assert.True(true);
        }

        [Fact]
        public void DataValidate()
        {
            Dictionary<string, string> shapes = new Dictionary<string, string>();

            #region domainShape
            StringBuilder domainShape = new StringBuilder();
            domainShape.AppendLine("@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.");
            domainShape.AppendLine("@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.");
            domainShape.AppendLine("@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.");
            domainShape.AppendLine("@prefix xml: <http://www.w3.org/XML/1998/namespace>.");
            domainShape.AppendLine("@prefix ns: <http://www.w3.org/2003/06/sw-vocab-status/ns#>.");
            domainShape.AppendLine("@prefix ro: <http://purl.org/roh/mirror/obo/ro#>.");
            domainShape.AppendLine("@prefix bfo: <http://purl.org/roh/mirror/obo/bfo#>.");
            domainShape.AppendLine("@prefix iao: <http://purl.org/roh/mirror/obo/iao#>.");
            domainShape.AppendLine("@prefix obo: <http://purl.obolibrary.org/obo/>.");
            domainShape.AppendLine("@prefix owl: <http://www.w3.org/2002/07/owl#>.");
            domainShape.AppendLine("@prefix bibo: <http://purl.org/roh/mirror/bibo#>.");
            domainShape.AppendLine("@prefix foaf: <https://xmlns.com/foaf/0.1/>.");
            domainShape.AppendLine("@prefix iao1: <http://purl.org/roh/mirror/obo/iao#>.");
            domainShape.AppendLine("@prefix skos: <http://www.w3.org/2004/02/skos/core#>.");
            domainShape.AppendLine("@prefix vivo: <http://purl.org/roh/mirror/vivo#>.");
            domainShape.AppendLine("@prefix skos1: <http://purl.org/roh/mirror/skos#>.");
            domainShape.AppendLine("@prefix terms: <http://purl.org/dc/terms/>.");
            domainShape.AppendLine("@prefix vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>.");
            domainShape.AppendLine("@prefix uneskos: <http://purl.org/umu/uneskos#>.");
            domainShape.AppendLine("@prefix skos-thes: <http://purl.org/iso25964/skos-thes#>.");
            domainShape.AppendLine("@prefix sh: <http://www.w3.org/ns/shacl#>.");
            domainShape.AppendLine("@prefix roh: <http://purl.org/roh#>.");
            domainShape.AppendLine("@prefix foaf1: <http://purl.org/roh/mirror/foaf#>.");
            domainShape.AppendLine("@prefix vcard: <http://purl.org/roh/mirror/vcard#>.");
            domainShape.AppendLine("@prefix geonames: <http://purl.org/roh/mirror/geonames#>.");
            domainShape.AppendLine("@prefix ero: <http://purl.org/roh/mirror/obo/ero#>.");
            domainShape.AppendLine("roh:domainroh__accreditationOfShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:accreditationOf ;");
            domainShape.AppendLine("	sh:class roh:Accreditation.");
            domainShape.AppendLine("roh:domainroh__issuedByShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:issuedBy ;");
            domainShape.AppendLine("	sh:class roh:Accreditation.");
            domainShape.AppendLine("roh:domainroh__issuesShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:issues ;");
            domainShape.AppendLine("	sh:class roh:AccreditationIssuer.");
            domainShape.AppendLine("roh:domainroh__participatedByShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:participatedBy ;");
            domainShape.AppendLine("	sh:class roh:Activity.");
            domainShape.AppendLine("roh:domainbfo__BFO_0000055Shape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf bfo:BFO_0000055 ;");
            domainShape.AppendLine("	sh:class roh:Activity.");
            domainShape.AppendLine("roh:domainroh__CVOfShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:CVOf ;");
            domainShape.AppendLine("	sh:class roh:CurriculumVitae.");
            domainShape.AppendLine("roh:domainroh__citesShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:cites ;");
            domainShape.AppendLine("	sh:class roh:CurriculumVitae.");
            domainShape.AppendLine("roh:domainroh__factorHShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:factorH ;");
            domainShape.AppendLine("	sh:class roh:CurriculumVitae.");
            domainShape.AppendLine("roh:domainroh__summaryShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:summary ;");
            domainShape.AppendLine("	sh:class roh:CurriculumVitae.");
            domainShape.AppendLine("roh:domainroh__spentByShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:spentBy ;");
            domainShape.AppendLine("	sh:class roh:Expense.");
            domainShape.AppendLine("roh:domainroh__supportsShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:supports ;");
            domainShape.AppendLine("	sh:class roh:Funding.");
            domainShape.AppendLine("roh:domainroh__publicFundingShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:publicFunding ;");
            domainShape.AppendLine("	sh:class roh:Funding.");
            domainShape.AppendLine("roh:domainroh__grantsShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:grants ;");
            domainShape.AppendLine("	sh:class roh:FundingAmount.");
            domainShape.AppendLine("roh:domainroh__infrastructureOfShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:infrastructureOf ;");
            domainShape.AppendLine("	sh:class roh:Infrastructure.");
            domainShape.AppendLine("roh:domainroh__languageSkillShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:languageSkill ;");
            domainShape.AppendLine("	sh:class roh:LanguageCertificate.");
            domainShape.AppendLine("roh:domainroh__languageShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:language ;");
            domainShape.AppendLine("	sh:class roh:LanguageCertificate.");
            domainShape.AppendLine("roh:domainroh__metricOfShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:metricOf ;");
            domainShape.AppendLine("	sh:class roh:Metric.");
            domainShape.AppendLine("roh:domainroh__metricNameShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:metricName ;");
            domainShape.AppendLine("	sh:class roh:Metric.");
            domainShape.AppendLine("roh:domainroh__markShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:mark ;");
            domainShape.AppendLine("	sh:class roh:PhDThesisMetric.");
            domainShape.AppendLine("roh:domainroh__cumLaudeShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:cumLaude ;");
            domainShape.AppendLine("	sh:class roh:PhDThesisMetric.");
            domainShape.AppendLine("roh:domainroh__impactFactorShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:impactFactor ;");
            domainShape.AppendLine("	sh:class roh:PublicationMetric.");
            domainShape.AppendLine("roh:domainroh__quartileShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:quartile ;");
            domainShape.AppendLine("	sh:class roh:PublicationMetric.");
            domainShape.AppendLine("roh:domainroh__rankingShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:ranking ;");
            domainShape.AppendLine("	sh:class roh:PublicationMetric.");
            domainShape.AppendLine("roh:domainroh__hasMetricShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:hasMetric ;");
            domainShape.AppendLine("	sh:class roh:ResearchObject.");
            domainShape.AppendLine("roh:domainbibo__issueShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf bibo:issue ;");
            domainShape.AppendLine("	sh:or ( ");
            domainShape.AppendLine("		[sh:class bibo:Article]");
            domainShape.AppendLine("		[sh:class bibo:Issue]");
            domainShape.AppendLine("	). ");
            domainShape.AppendLine("roh:domainbibo__editorListShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf bibo:editorList ;");
            domainShape.AppendLine("	sh:class bibo:Document.");
            domainShape.AppendLine("roh:domainbibo__authorListShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf bibo:authorList ;");
            domainShape.AppendLine("	sh:class bibo:Document.");
            domainShape.AppendLine("roh:domainbibo__pageEndShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf bibo:pageEnd ;");
            domainShape.AppendLine("	sh:class bibo:Document.");
            domainShape.AppendLine("roh:domainbibo__pageStartShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf bibo:pageStart ;");
            domainShape.AppendLine("	sh:class bibo:Document.");
            domainShape.AppendLine("roh:domainbibo__volumeShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf bibo:volume ;");
            domainShape.AppendLine("	sh:class bibo:Document.");
            domainShape.AppendLine("roh:domainroh__ownerOrganizationShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:ownerOrganization ;");
            domainShape.AppendLine("	sh:class bibo:Patent.");
            domainShape.AppendLine("roh:domainroh__statusShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:status ;");
            domainShape.AppendLine("	sh:class bibo:Report.");
            domainShape.AppendLine("roh:domainroh__hasInfrastructureShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:hasInfrastructure ;");
            domainShape.AppendLine("	sh:class foaf1:Agent.");
            domainShape.AppendLine("roh:domainroh__supervisedByShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:supervisedBy ;");
            domainShape.AppendLine("	sh:class bibo:Thesis.");
            domainShape.AppendLine("roh:domainroh__hasRoleShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:hasRole ;");
            domainShape.AppendLine("	sh:class foaf1:Agent.");
            domainShape.AppendLine("roh:domainroh__hasAccreditationShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:hasAccreditation ;");
            domainShape.AppendLine("	sh:class foaf1:Agent.");
            domainShape.AppendLine("roh:domainfoaf1__mboxShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf foaf1:mbox ;");
            domainShape.AppendLine("	sh:class foaf1:Agent.");
            domainShape.AppendLine("roh:domainroh__hasContactInfoShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:hasContactInfo ;");
            domainShape.AppendLine("	sh:class foaf1:Agent.");
            domainShape.AppendLine("roh:domainroh__grantedByShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:grantedBy ;");
            domainShape.AppendLine("	sh:class foaf1:Organization.");
            domainShape.AppendLine("roh:domainroh__providesShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:provides ;");
            domainShape.AppendLine("	sh:class foaf1:Organization.");
            domainShape.AppendLine("roh:domainroh__foundationDateShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:foundationDate ;");
            domainShape.AppendLine("	sh:class foaf1:Organization.");
            domainShape.AppendLine("roh:domainvivo__affiliatedOrganizationShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf vivo:affiliatedOrganization ;");
            domainShape.AppendLine("	sh:class foaf1:Organization.");
            domainShape.AppendLine("roh:domainroh__correspondingAuthorOfShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:correspondingAuthorOf ;");
            domainShape.AppendLine("	sh:class foaf1:Person.");
            domainShape.AppendLine("roh:domainvivo__hasPredecessorOrganizationShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf vivo:hasPredecessorOrganization ;");
            domainShape.AppendLine("	sh:class foaf1:Organization.");
            domainShape.AppendLine("roh:domainroh__ownerOrganizationOfShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:ownerOrganizationOf ;");
            domainShape.AppendLine("	sh:class foaf1:Organization.");
            domainShape.AppendLine("roh:domainroh__hasCVShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:hasCV ;");
            domainShape.AppendLine("	sh:class foaf1:Person.");
            domainShape.AppendLine("roh:domainvivo__hasSuccessorOrganizationShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf vivo:hasSuccessorOrganization ;");
            domainShape.AppendLine("	sh:class foaf1:Organization.");
            domainShape.AppendLine("roh:domainroh__supervisorOfShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:supervisorOf ;");
            domainShape.AppendLine("	sh:class foaf1:Person.");
            domainShape.AppendLine("roh:domainroh__hasPositionShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:hasPosition ;");
            domainShape.AppendLine("	sh:class foaf1:Person.");
            domainShape.AppendLine("roh:domainfoaf1__imgShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf foaf1:img ;");
            domainShape.AppendLine("	sh:class foaf1:Person.");
            domainShape.AppendLine("roh:domainfoaf1__genderShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf foaf1:gender ;");
            domainShape.AppendLine("	sh:class foaf1:Person.");
            domainShape.AppendLine("roh:domainfoaf1__surnameShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf foaf1:surname ;");
            domainShape.AppendLine("	sh:class foaf1:Person.");
            domainShape.AppendLine("roh:domainvivo__researcherIdShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf vivo:researcherId ;");
            domainShape.AppendLine("	sh:class foaf1:Person.");
            domainShape.AppendLine("roh:domainvivo__eRACommonsIdShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf vivo:eRACommonsId ;");
            domainShape.AppendLine("	sh:class foaf1:Person.");
            domainShape.AppendLine("roh:domainvivo__scopusIdShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf vivo:scopusId ;");
            domainShape.AppendLine("	sh:class foaf1:Person.");
            domainShape.AppendLine("roh:domainroh__roleOfShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:roleOf ;");
            domainShape.AppendLine("	sh:class bfo:BFO_0000023.");
            domainShape.AppendLine("roh:domainroh__dedicationShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:dedication ;");
            domainShape.AppendLine("	sh:class bfo:BFO_0000023.");
            domainShape.AppendLine("roh:domainbfo__BFO_0000054Shape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf bfo:BFO_0000054 ;");
            domainShape.AppendLine("	sh:class bfo:BFO_0000023.");
            domainShape.AppendLine("roh:domainroh__isProvidedByShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:isProvidedBy ;");
            domainShape.AppendLine("	sh:class ero:ERO_0000005.");
            domainShape.AppendLine("roh:domainroh__contactInfoOfShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:contactInfoOf ;");
            domainShape.AppendLine("	sh:class vcard:Kind.");
            domainShape.AppendLine("roh:domainroh__awardedByShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:awardedBy ;");
            domainShape.AppendLine("	sh:class vivo:AwardedDegree.");
            domainShape.AppendLine("roh:domainvivo__degreeCandidacyShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf vivo:degreeCandidacy ;");
            domainShape.AppendLine("	sh:class vivo:AdvisingRelationship.");
            domainShape.AppendLine("roh:domainroh__contractOfShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:contractOf ;");
            domainShape.AppendLine("	sh:class vivo:Contract.");
            domainShape.AppendLine("roh:domainvivo__endShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf vivo:end ;");
            domainShape.AppendLine("	sh:class vivo:DateTimeInterval.");
            domainShape.AppendLine("roh:domainroh__contractSigningDateShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:contractSigningDate ;");
            domainShape.AppendLine("	sh:class vivo:Contract.");
            domainShape.AppendLine("roh:domainvivo__startShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf vivo:start ;");
            domainShape.AppendLine("	sh:class vivo:DateTimeInterval.");
            domainShape.AppendLine("roh:domainroh__contractSigningDateOfShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:contractSigningDateOf ;");
            domainShape.AppendLine("	sh:class vivo:DateTimeValue.");
            domainShape.AppendLine("roh:domainroh__positionOfShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:positionOf ;");
            domainShape.AppendLine("	sh:class vivo:Position.");
            domainShape.AppendLine("roh:domainroh__promotesShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:promotes ;");
            domainShape.AppendLine("	sh:class vivo:FundingOrganization.");
            domainShape.AppendLine("roh:domainvivo__hrJobTitleShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf vivo:hrJobTitle ;");
            domainShape.AppendLine("	sh:class vivo:Position.");
            domainShape.AppendLine("roh:domainroh__modalityShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:modality ;");
            domainShape.AppendLine("	sh:class vivo:Project.");
            domainShape.AppendLine("roh:domainroh__isSupportedByShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:isSupportedBy ;");
            domainShape.AppendLine("	sh:class vivo:Project.");
            domainShape.AppendLine("roh:domainroh__projectStatusShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:projectStatus ;");
            domainShape.AppendLine("	sh:class vivo:Project.");
            domainShape.AppendLine("roh:domainroh__foreseenJustificationDateShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:foreseenJustificationDate ;");
            domainShape.AppendLine("	sh:class vivo:Project.");
            domainShape.AppendLine("roh:domainroh__awardsShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:awards ;");
            domainShape.AppendLine("	sh:class vivo:University.");
            domainShape.AppendLine("roh:domainroh__promotedByShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:promotedBy ;");
            domainShape.AppendLine("	sh:or ( ");
            domainShape.AppendLine("		[sh:class roh:FundingSource]");
            domainShape.AppendLine("		[sh:class roh:FundingProgram]");
            domainShape.AppendLine("	). ");
            domainShape.AppendLine("roh:domainroh__knowledgeAreaOfShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:knowledgeAreaOf ;");
            domainShape.AppendLine("	sh:class skos:Concept.");
            domainShape.AppendLine("roh:domainroh__ORCIDShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:ORCID ;");
            domainShape.AppendLine("	sh:class foaf1:Person.");
            domainShape.AppendLine("roh:domainroh__taxIDShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf roh:taxID ;");
            domainShape.AppendLine("	sh:class foaf1:Person.");
            domainShape.AppendLine("roh:domainfoaf1__firstNameShape");
            domainShape.AppendLine("	a sh:NodeShape ;");
            domainShape.AppendLine("	sh:targetSubjectsOf foaf1:firstName ;");
            domainShape.AppendLine("	sh:class foaf1:Person.");
            shapes.Add("DomainShape", domainShape.ToString());
            #endregion

            #region RangeDatatypeShape
            StringBuilder rangeDatatypeShape = new StringBuilder();
            rangeDatatypeShape.AppendLine("@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.");
            rangeDatatypeShape.AppendLine("@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.");
            rangeDatatypeShape.AppendLine("@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.");
            rangeDatatypeShape.AppendLine("@prefix xml: <http://www.w3.org/XML/1998/namespace>.");
            rangeDatatypeShape.AppendLine("@prefix ns: <http://www.w3.org/2003/06/sw-vocab-status/ns#>.");
            rangeDatatypeShape.AppendLine("@prefix ro: <http://purl.org/roh/mirror/obo/ro#>.");
            rangeDatatypeShape.AppendLine("@prefix bfo: <http://purl.org/roh/mirror/obo/bfo#>.");
            rangeDatatypeShape.AppendLine("@prefix iao: <http://purl.org/roh/mirror/obo/iao#>.");
            rangeDatatypeShape.AppendLine("@prefix obo: <http://purl.obolibrary.org/obo/>.");
            rangeDatatypeShape.AppendLine("@prefix owl: <http://www.w3.org/2002/07/owl#>.");
            rangeDatatypeShape.AppendLine("@prefix bibo: <http://purl.org/roh/mirror/bibo#>.");
            rangeDatatypeShape.AppendLine("@prefix foaf: <https://xmlns.com/foaf/0.1/>.");
            rangeDatatypeShape.AppendLine("@prefix iao1: <http://purl.org/roh/mirror/obo/iao#>.");
            rangeDatatypeShape.AppendLine("@prefix skos: <http://www.w3.org/2004/02/skos/core#>.");
            rangeDatatypeShape.AppendLine("@prefix vivo: <http://purl.org/roh/mirror/vivo#>.");
            rangeDatatypeShape.AppendLine("@prefix skos1: <http://purl.org/roh/mirror/skos#>.");
            rangeDatatypeShape.AppendLine("@prefix terms: <http://purl.org/dc/terms/>.");
            rangeDatatypeShape.AppendLine("@prefix vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>.");
            rangeDatatypeShape.AppendLine("@prefix uneskos: <http://purl.org/umu/uneskos#>.");
            rangeDatatypeShape.AppendLine("@prefix skos-thes: <http://purl.org/iso25964/skos-thes#>.");
            rangeDatatypeShape.AppendLine("@prefix sh: <http://www.w3.org/ns/shacl#>.");
            rangeDatatypeShape.AppendLine("@prefix roh: <http://purl.org/roh#>.");
            rangeDatatypeShape.AppendLine("@prefix foaf1: <http://purl.org/roh/mirror/foaf#>.");
            rangeDatatypeShape.AppendLine("@prefix vcard: <http://purl.org/roh/mirror/vcard#>.");
            rangeDatatypeShape.AppendLine("@prefix geonames: <http://purl.org/roh/mirror/geonames#>.");
            rangeDatatypeShape.AppendLine("@prefix ero: <http://purl.org/roh/mirror/obo/ero#>.");
            rangeDatatypeShape.AppendLine("roh:rangeDatatyperoh__birthdateShape");
            rangeDatatypeShape.AppendLine("	a sh:NodeShape ;");
            rangeDatatypeShape.AppendLine("	sh:targetObjectsOf  roh:birthdate ;");
            rangeDatatypeShape.AppendLine("	sh:datatype xsd:dateTime.");
            rangeDatatypeShape.AppendLine("roh:rangeDatatyperoh__cumLaudeShape");
            rangeDatatypeShape.AppendLine("	a sh:NodeShape ;");
            rangeDatatypeShape.AppendLine("	sh:targetObjectsOf  roh:cumLaude ;");
            rangeDatatypeShape.AppendLine("	sh:datatype xsd:boolean.");
            rangeDatatypeShape.AppendLine("roh:rangeDatatyperoh__excellenceLabelShape");
            rangeDatatypeShape.AppendLine("	a sh:NodeShape ;");
            rangeDatatypeShape.AppendLine("	sh:targetObjectsOf  roh:excellenceLabel ;");
            rangeDatatypeShape.AppendLine("	sh:datatype xsd:boolean.");
            rangeDatatypeShape.AppendLine("roh:rangeDatatyperoh__foreseenJustificationDateShape");
            rangeDatatypeShape.AppendLine("	a sh:NodeShape ;");
            rangeDatatypeShape.AppendLine("	sh:targetObjectsOf  roh:foreseenJustificationDate ;");
            rangeDatatypeShape.AppendLine("	sh:datatype xsd:dateTime.");
            rangeDatatypeShape.AppendLine("roh:rangeDatatyperoh__foundationDateShape");
            rangeDatatypeShape.AppendLine("	a sh:NodeShape ;");
            rangeDatatypeShape.AppendLine("	sh:targetObjectsOf  roh:foundationDate ;");
            rangeDatatypeShape.AppendLine("	sh:datatype xsd:dateTime.");
            rangeDatatypeShape.AppendLine("roh:rangeDatatyperoh__impactFactorShape");
            rangeDatatypeShape.AppendLine("	a sh:NodeShape ;");
            rangeDatatypeShape.AppendLine("	sh:targetObjectsOf  roh:impactFactor ;");
            rangeDatatypeShape.AppendLine("	sh:datatype xsd:float.");
            rangeDatatypeShape.AppendLine("roh:rangeDatatyperoh__languageShape");
            rangeDatatypeShape.AppendLine("	a sh:NodeShape ;");
            rangeDatatypeShape.AppendLine("	sh:targetObjectsOf  roh:language ;");
            rangeDatatypeShape.AppendLine("	sh:datatype xsd:string.");
            rangeDatatypeShape.AppendLine("roh:rangeDatatyperoh__markShape");
            rangeDatatypeShape.AppendLine("	a sh:NodeShape ;");
            rangeDatatypeShape.AppendLine("	sh:targetObjectsOf  roh:mark ;");
            rangeDatatypeShape.AppendLine("	sh:datatype xsd:string.");
            rangeDatatypeShape.AppendLine("roh:rangeDatatyperoh__modalityShape");
            rangeDatatypeShape.AppendLine("	a sh:NodeShape ;");
            rangeDatatypeShape.AppendLine("	sh:targetObjectsOf  roh:modality ;");
            rangeDatatypeShape.AppendLine("	sh:datatype xsd:string.");
            rangeDatatypeShape.AppendLine("roh:rangeDatatyperoh__monetaryAmountShape");
            rangeDatatypeShape.AppendLine("	a sh:NodeShape ;");
            rangeDatatypeShape.AppendLine("	sh:targetObjectsOf  roh:monetaryAmount ;");
            rangeDatatypeShape.AppendLine("	sh:datatype xsd:decimal.");
            rangeDatatypeShape.AppendLine("roh:rangeDatatyperoh__needsEthicalValidationShape");
            rangeDatatypeShape.AppendLine("	a sh:NodeShape ;");
            rangeDatatypeShape.AppendLine("	sh:targetObjectsOf  roh:needsEthicalValidation ;");
            rangeDatatypeShape.AppendLine("	sh:datatype xsd:boolean.");
            rangeDatatypeShape.AppendLine("roh:rangeDatatyperoh__publicFundingShape");
            rangeDatatypeShape.AppendLine("	a sh:NodeShape ;");
            rangeDatatypeShape.AppendLine("	sh:targetObjectsOf  roh:publicFunding ;");
            rangeDatatypeShape.AppendLine("	sh:datatype xsd:boolean.");
            rangeDatatypeShape.AppendLine("roh:rangeDatatyperoh__rankingShape");
            rangeDatatypeShape.AppendLine("	a sh:NodeShape ;");
            rangeDatatypeShape.AppendLine("	sh:targetObjectsOf  roh:ranking ;");
            rangeDatatypeShape.AppendLine("	sh:datatype xsd:string.");
            rangeDatatypeShape.AppendLine("roh:rangeDatatyperoh__researchLineShape");
            rangeDatatypeShape.AppendLine("	a sh:NodeShape ;");
            rangeDatatypeShape.AppendLine("	sh:targetObjectsOf  roh:researchLine ;");
            rangeDatatypeShape.AppendLine("	sh:datatype xsd:string.");
            rangeDatatypeShape.AppendLine("roh:rangeDatatypebibo__issueShape");
            rangeDatatypeShape.AppendLine("	a sh:NodeShape ;");
            rangeDatatypeShape.AppendLine("	sh:targetObjectsOf  bibo:issue ;");
            rangeDatatypeShape.AppendLine("	sh:nodeKind sh:Literal.");
            rangeDatatypeShape.AppendLine("roh:rangeDatatypebibo__pageEndShape");
            rangeDatatypeShape.AppendLine("	a sh:NodeShape ;");
            rangeDatatypeShape.AppendLine("	sh:targetObjectsOf  bibo:pageEnd ;");
            rangeDatatypeShape.AppendLine("	sh:nodeKind sh:Literal.");
            rangeDatatypeShape.AppendLine("roh:rangeDatatypebibo__volumeShape");
            rangeDatatypeShape.AppendLine("	a sh:NodeShape ;");
            rangeDatatypeShape.AppendLine("	sh:targetObjectsOf  bibo:volume ;");
            rangeDatatypeShape.AppendLine("	sh:nodeKind sh:Literal.");
            rangeDatatypeShape.AppendLine("roh:rangeDatatypefoaf1__firstNameShape");
            rangeDatatypeShape.AppendLine("	a sh:NodeShape ;");
            rangeDatatypeShape.AppendLine("	sh:targetObjectsOf  foaf1:firstName ;");
            rangeDatatypeShape.AppendLine("	sh:nodeKind sh:Literal.");
            rangeDatatypeShape.AppendLine("roh:rangeDatatypebibo__pageStartShape");
            rangeDatatypeShape.AppendLine("	a sh:NodeShape ;");
            rangeDatatypeShape.AppendLine("	sh:targetObjectsOf  bibo:pageStart ;");
            rangeDatatypeShape.AppendLine("	sh:nodeKind sh:Literal.");
            rangeDatatypeShape.AppendLine("roh:rangeDatatypefoaf1__genderShape");
            rangeDatatypeShape.AppendLine("	a sh:NodeShape ;");
            rangeDatatypeShape.AppendLine("	sh:targetObjectsOf  foaf1:gender ;");
            rangeDatatypeShape.AppendLine("	sh:nodeKind sh:Literal.");
            rangeDatatypeShape.AppendLine("roh:rangeDatatypefoaf1__nameShape");
            rangeDatatypeShape.AppendLine("	a sh:NodeShape ;");
            rangeDatatypeShape.AppendLine("	sh:targetObjectsOf  foaf1:name ;");
            rangeDatatypeShape.AppendLine("	sh:nodeKind sh:Literal.");
            rangeDatatypeShape.AppendLine("roh:rangeDatatypefoaf1__surnameShape");
            rangeDatatypeShape.AppendLine("	a sh:NodeShape ;");
            rangeDatatypeShape.AppendLine("	sh:targetObjectsOf  foaf1:surname ;");
            rangeDatatypeShape.AppendLine("	sh:nodeKind sh:Literal.");
            rangeDatatypeShape.AppendLine("roh:rangeDatatypevivo__dateTimeShape");
            rangeDatatypeShape.AppendLine("	a sh:NodeShape ;");
            rangeDatatypeShape.AppendLine("	sh:targetObjectsOf  vivo:dateTime ;");
            rangeDatatypeShape.AppendLine("	sh:datatype xsd:dateTime.");
            shapes.Add("RangeDatatypeShape", rangeDatatypeShape.ToString());
            #endregion

            #region RangeObjectShape
            StringBuilder rangeObjectShape = new StringBuilder();
            rangeObjectShape.AppendLine("@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.");
            rangeObjectShape.AppendLine("@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.");
            rangeObjectShape.AppendLine("@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.");
            rangeObjectShape.AppendLine("@prefix xml: <http://www.w3.org/XML/1998/namespace>.");
            rangeObjectShape.AppendLine("@prefix ns: <http://www.w3.org/2003/06/sw-vocab-status/ns#>.");
            rangeObjectShape.AppendLine("@prefix ro: <http://purl.org/roh/mirror/obo/ro#>.");
            rangeObjectShape.AppendLine("@prefix bfo: <http://purl.org/roh/mirror/obo/bfo#>.");
            rangeObjectShape.AppendLine("@prefix iao: <http://purl.org/roh/mirror/obo/iao#>.");
            rangeObjectShape.AppendLine("@prefix obo: <http://purl.obolibrary.org/obo/>.");
            rangeObjectShape.AppendLine("@prefix owl: <http://www.w3.org/2002/07/owl#>.");
            rangeObjectShape.AppendLine("@prefix bibo: <http://purl.org/roh/mirror/bibo#>.");
            rangeObjectShape.AppendLine("@prefix foaf: <https://xmlns.com/foaf/0.1/>.");
            rangeObjectShape.AppendLine("@prefix iao1: <http://purl.org/roh/mirror/obo/iao#>.");
            rangeObjectShape.AppendLine("@prefix skos: <http://www.w3.org/2004/02/skos/core#>.");
            rangeObjectShape.AppendLine("@prefix vivo: <http://purl.org/roh/mirror/vivo#>.");
            rangeObjectShape.AppendLine("@prefix skos1: <http://purl.org/roh/mirror/skos#>.");
            rangeObjectShape.AppendLine("@prefix terms: <http://purl.org/dc/terms/>.");
            rangeObjectShape.AppendLine("@prefix vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>.");
            rangeObjectShape.AppendLine("@prefix uneskos: <http://purl.org/umu/uneskos#>.");
            rangeObjectShape.AppendLine("@prefix skos-thes: <http://purl.org/iso25964/skos-thes#>.");
            rangeObjectShape.AppendLine("@prefix sh: <http://www.w3.org/ns/shacl#>.");
            rangeObjectShape.AppendLine("@prefix roh: <http://purl.org/roh#>.");
            rangeObjectShape.AppendLine("@prefix foaf1: <http://purl.org/roh/mirror/foaf#>.");
            rangeObjectShape.AppendLine("@prefix vcard: <http://purl.org/roh/mirror/vcard#>.");
            rangeObjectShape.AppendLine("@prefix geonames: <http://purl.org/roh/mirror/geonames#>.");
            rangeObjectShape.AppendLine("@prefix ero: <http://purl.org/roh/mirror/obo/ero#>.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__CVOfShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:CVOf ;");
            rangeObjectShape.AppendLine("	sh:class foaf1:Person.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__awardsShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:awards ;");
            rangeObjectShape.AppendLine("	sh:class vivo:AwardedDegree.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__contactInfoOfShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:contactInfoOf ;");
            rangeObjectShape.AppendLine("	sh:class foaf1:Agent.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__accreditationOfShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:accreditationOf ;");
            rangeObjectShape.AppendLine("	sh:class foaf1:Agent.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__awardedByShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:awardedBy ;");
            rangeObjectShape.AppendLine("	sh:class vivo:University.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__contractSigningDateShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:contractSigningDate ;");
            rangeObjectShape.AppendLine("	sh:class vivo:DateTimeValue.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__contractSigningDateOfShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:contractSigningDateOf ;");
            rangeObjectShape.AppendLine("	sh:class vivo:Contract.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__correspondingAuthorShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:correspondingAuthor ;");
            rangeObjectShape.AppendLine("	sh:class foaf1:Person.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__grantedByShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:grantedBy ;");
            rangeObjectShape.AppendLine("	sh:class roh:FundingAmount.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__grantsShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:grants ;");
            rangeObjectShape.AppendLine("	sh:class foaf1:Organization.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__hasAccreditationShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:hasAccreditation ;");
            rangeObjectShape.AppendLine("	sh:class roh:Accreditation.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__hasCVShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:hasCV ;");
            rangeObjectShape.AppendLine("	sh:class roh:CurriculumVitae.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__hasContactInfoShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:hasContactInfo ;");
            rangeObjectShape.AppendLine("	sh:class vcard:Kind.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__hasContractShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:hasContract ;");
            rangeObjectShape.AppendLine("	sh:class vivo:Contract.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__hasInfrastructureShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:hasInfrastructure ;");
            rangeObjectShape.AppendLine("	sh:class roh:Infrastructure.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__hasKnowledgeAreaShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:hasKnowledgeArea ;");
            rangeObjectShape.AppendLine("	sh:class skos:Concept.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__hasMetricShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:hasMetric ;");
            rangeObjectShape.AppendLine("	sh:class roh:Metric.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__hasRoleShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:hasRole ;");
            rangeObjectShape.AppendLine("	sh:class bfo:BFO_0000023.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__infrastructureOfShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:infrastructureOf ;");
            rangeObjectShape.AppendLine("	sh:class foaf1:Agent.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__isProvidedByShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:isProvidedBy ;");
            rangeObjectShape.AppendLine("	sh:class foaf1:Organization.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__hasPositionShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:hasPosition ;");
            rangeObjectShape.AppendLine("	sh:class vivo:Position.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__isSupportedByShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:isSupportedBy ;");
            rangeObjectShape.AppendLine("	sh:class roh:Funding.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__issuedByShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:issuedBy ;");
            rangeObjectShape.AppendLine("	sh:class roh:AccreditationIssuer.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__issuesShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:issues ;");
            rangeObjectShape.AppendLine("	sh:class roh:Accreditation.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__metricOfShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:metricOf ;");
            rangeObjectShape.AppendLine("	sh:class roh:ResearchObject.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__ownerOrganizationShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:ownerOrganization ;");
            rangeObjectShape.AppendLine("	sh:class foaf1:Organization.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__ownerOrganizationOfShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:ownerOrganizationOf ;");
            rangeObjectShape.AppendLine("	sh:class bibo:Patent.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__participatesShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:participates ;");
            rangeObjectShape.AppendLine("	sh:class roh:Activity.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__producedByShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:producedBy ;");
            rangeObjectShape.AppendLine("	sh:class owl:Thing.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__promotedByShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:promotedBy ;");
            rangeObjectShape.AppendLine("	sh:class vivo:FundingOrganization.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__positionOfShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:positionOf ;");
            rangeObjectShape.AppendLine("	sh:class foaf1:Person.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__roleOfShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:roleOf ;");
            rangeObjectShape.AppendLine("	sh:class foaf1:Agent.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__spendsShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:spends ;");
            rangeObjectShape.AppendLine("	sh:class roh:Expense.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__providesShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:provides ;");
            rangeObjectShape.AppendLine("	sh:class ero:ERO_0000005.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__supervisedByShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:supervisedBy ;");
            rangeObjectShape.AppendLine("	sh:class foaf1:Person.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__supervisorOfShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:supervisorOf ;");
            rangeObjectShape.AppendLine("	sh:class bibo:Thesis.");
            rangeObjectShape.AppendLine("roh:rangeClassfoaf1__imgShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  foaf1:img ;");
            rangeObjectShape.AppendLine("	sh:class foaf1:Image.");
            rangeObjectShape.AppendLine("roh:rangeClassfoaf1__homepageShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  foaf1:homepage ;");
            rangeObjectShape.AppendLine("	sh:class foaf1:Document.");
            rangeObjectShape.AppendLine("roh:rangeClassgeonames__locatedInShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  geonames:locatedIn ;");
            rangeObjectShape.AppendLine("	sh:class geonames:Feature.");
            rangeObjectShape.AppendLine("roh:rangeClassbfo__BFO_0000054Shape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  bfo:BFO_0000054 ;");
            rangeObjectShape.AppendLine("	sh:class roh:Activity.");
            rangeObjectShape.AppendLine("roh:rangeClassfoaf1__mboxShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  foaf1:mbox ;");
            rangeObjectShape.AppendLine("	sh:class owl:Thing.");
            rangeObjectShape.AppendLine("roh:rangeClassbfo__BFO_0000055Shape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  bfo:BFO_0000055 ;");
            rangeObjectShape.AppendLine("	sh:class bfo:BFO_0000023.");
            rangeObjectShape.AppendLine("roh:rangeClassvivo__degreeCandidacyShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  vivo:degreeCandidacy ;");
            rangeObjectShape.AppendLine("	sh:class vivo:AcademicDegree.");
            rangeObjectShape.AppendLine("roh:rangeClassvivo__affiliatedOrganizationShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  vivo:affiliatedOrganization ;");
            rangeObjectShape.AppendLine("	sh:class foaf1:Organization.");
            rangeObjectShape.AppendLine("roh:rangeClassvivo__endShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  vivo:end ;");
            rangeObjectShape.AppendLine("	sh:class vivo:DateTimeValue.");
            rangeObjectShape.AppendLine("roh:rangeClassvivo__hasSuccessorOrganizationShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  vivo:hasSuccessorOrganization ;");
            rangeObjectShape.AppendLine("	sh:class foaf1:Organization.");
            rangeObjectShape.AppendLine("roh:rangeClassvivo__dateIssuedShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  vivo:dateIssued ;");
            rangeObjectShape.AppendLine("	sh:class vivo:DateTimeValue.");
            rangeObjectShape.AppendLine("roh:rangeClassbibo__editorListShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  bibo:editorList ;");
            rangeObjectShape.AppendLine("	sh:or ( ");
            rangeObjectShape.AppendLine("		[sh:class rdf:List]");
            rangeObjectShape.AppendLine("		[sh:class rdf:Seq]");
            rangeObjectShape.AppendLine("	). ");
            rangeObjectShape.AppendLine("roh:rangeClassvivo__hasPredecessorOrganizationShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  vivo:hasPredecessorOrganization ;");
            rangeObjectShape.AppendLine("	sh:class foaf1:Organization.");
            rangeObjectShape.AppendLine("roh:rangeClassvivo__startShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  vivo:start ;");
            rangeObjectShape.AppendLine("	sh:class vivo:DateTimeValue.");
            rangeObjectShape.AppendLine("roh:rangeClassroh__promotesShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:promotes ;");
            rangeObjectShape.AppendLine("	sh:or ( ");
            rangeObjectShape.AppendLine("		[sh:class roh:FundingProgram]");
            rangeObjectShape.AppendLine("		[sh:class roh:FundingSource]");
            rangeObjectShape.AppendLine("	). ");
            rangeObjectShape.AppendLine("roh:rangeClassbibo__authorListShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  bibo:authorList ;");
            rangeObjectShape.AppendLine("	sh:or ( ");
            rangeObjectShape.AppendLine("		[sh:class rdf:Seq]");
            rangeObjectShape.AppendLine("		[sh:class rdf:List]");
            rangeObjectShape.AppendLine("	). ");
            rangeObjectShape.AppendLine("roh:rangeClassroh__supportsShape");
            rangeObjectShape.AppendLine("	a sh:NodeShape ;");
            rangeObjectShape.AppendLine("	sh:targetObjectsOf  roh:supports ;");
            rangeObjectShape.AppendLine("	sh:or ( ");
            rangeObjectShape.AppendLine("		[sh:class vivo:Project]");
            rangeObjectShape.AppendLine("		[sh:class roh:PersonContract]");
            rangeObjectShape.AppendLine("	). ");
            shapes.Add("RangeObjectShape", rangeObjectShape.ToString());
            #endregion

            #region personShape
            StringBuilder personShape = new StringBuilder();
            personShape.AppendLine("@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.");
            personShape.AppendLine("@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.");
            personShape.AppendLine("@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.");
            personShape.AppendLine("@prefix xml: <http://www.w3.org/XML/1998/namespace>.");
            personShape.AppendLine("@prefix ns: <http://www.w3.org/2003/06/sw-vocab-status/ns#>.");
            personShape.AppendLine("@prefix ro: <http://purl.org/roh/mirror/obo/ro#>.");
            personShape.AppendLine("@prefix bfo: <http://purl.org/roh/mirror/obo/bfo#>.");
            personShape.AppendLine("@prefix iao: <http://purl.org/roh/mirror/obo/iao#>.");
            personShape.AppendLine("@prefix obo: <http://purl.obolibrary.org/obo/>.");
            personShape.AppendLine("@prefix owl: <http://www.w3.org/2002/07/owl#>.");
            personShape.AppendLine("@prefix bibo: <http://purl.org/roh/mirror/bibo#>.");
            personShape.AppendLine("@prefix foaf: <https://xmlns.com/foaf/0.1/>.");
            personShape.AppendLine("@prefix iao1: <http://purl.org/roh/mirror/obo/iao#>.");
            personShape.AppendLine("@prefix skos: <http://www.w3.org/2004/02/skos/core#>.");
            personShape.AppendLine("@prefix vivo: <http://purl.org/roh/mirror/vivo#>.");
            personShape.AppendLine("@prefix skos1: <http://purl.org/roh/mirror/skos#>.");
            personShape.AppendLine("@prefix terms: <http://purl.org/dc/terms/>.");
            personShape.AppendLine("@prefix vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>.");
            personShape.AppendLine("@prefix uneskos: <http://purl.org/umu/uneskos#>.");
            personShape.AppendLine("@prefix skos-thes: <http://purl.org/iso25964/skos-thes#>.");
            personShape.AppendLine("@prefix sh: <http://www.w3.org/ns/shacl#>.");
            personShape.AppendLine("@prefix roh: <http://purl.org/roh#>.");
            personShape.AppendLine("@prefix foaf1: <http://purl.org/roh/mirror/foaf#>.");
            personShape.AppendLine("@prefix vcard: <http://purl.org/roh/mirror/vcard#>.");
            personShape.AppendLine("roh:foaf1_PersonShape");
            personShape.AppendLine("	a sh:NodeShape ;");
            personShape.AppendLine("	sh:targetClass foaf1:Person ;");
            personShape.AppendLine("	sh:property roh:someValuesDataType__foaf1__Person__foaf1__firstName;");
            personShape.AppendLine("	sh:property roh:someValuesDataType__foaf1__Person__vivo__identifier;");
            personShape.AppendLine("	sh:property roh:someValuesDataType__foaf1__Person__foaf1__surname;");
            personShape.AppendLine("	sh:property roh:allValuesDataType__foaf1__Person__foaf1__surname;");
            personShape.AppendLine("	sh:property roh:allValuesDataType__foaf1__Person__foaf1__firstName;");
            personShape.AppendLine("	sh:property roh:allValuesDataType__foaf1__Person__vivo__identifier.");
            personShape.AppendLine("roh:someValuesDataType__foaf1__Person__foaf1__firstName ");
            personShape.AppendLine("	sh:severity sh:Violation;");
            personShape.AppendLine("	sh:path foaf1:firstName;");
            personShape.AppendLine("	sh:qualifiedMinCount  1;");
            personShape.AppendLine("	sh:qualifiedValueShape [");
            personShape.AppendLine("		sh:datatype xsd:string;");
            personShape.AppendLine("	].");
            personShape.AppendLine("roh:someValuesDataType__foaf1__Person__vivo__identifier ");
            personShape.AppendLine("	sh:severity sh:Violation;");
            personShape.AppendLine("	sh:path vivo:identifier;");
            personShape.AppendLine("	sh:qualifiedMinCount  1;");
            personShape.AppendLine("	sh:qualifiedValueShape [");
            personShape.AppendLine("		sh:datatype xsd:string;");
            personShape.AppendLine("	].");
            personShape.AppendLine("roh:someValuesDataType__foaf1__Person__foaf1__surname ");
            personShape.AppendLine("	sh:severity sh:Violation;");
            personShape.AppendLine("	sh:path foaf1:surname;");
            personShape.AppendLine("	sh:qualifiedMinCount  1;");
            personShape.AppendLine("	sh:qualifiedValueShape [");
            personShape.AppendLine("		sh:datatype xsd:string;");
            personShape.AppendLine("	].");
            personShape.AppendLine("roh:allValuesDataType__foaf1__Person__foaf1__surname ");
            personShape.AppendLine("	sh:severity sh:Violation;");
            personShape.AppendLine("	sh:path foaf1:surname;");
            personShape.AppendLine("	sh:datatype xsd:string.");
            personShape.AppendLine("roh:allValuesDataType__foaf1__Person__foaf1__firstName ");
            personShape.AppendLine("	sh:severity sh:Violation;");
            personShape.AppendLine("	sh:path foaf1:firstName;");
            personShape.AppendLine("	sh:datatype xsd:string.");
            personShape.AppendLine("roh:allValuesDataType__foaf1__Person__vivo__identifier ");
            personShape.AppendLine("	sh:severity sh:Violation;");
            personShape.AppendLine("	sh:path vivo:identifier;");
            personShape.AppendLine("	sh:datatype xsd:string.");
            shapes.Add("PersonShape", personShape.ToString());
            #endregion

            List<ShapeConfig> listShapeConfig = shapes.Select(x => new ShapeConfig()
            {
                ShapeConfigID = Guid.NewGuid(),
                Name = x.Key,
                RepositoryID = Guid.NewGuid(),
                Shape = x.Value
            }).ToList();


            ShapeReport report = SparqlUtility.ValidateRDF(rdfFile, listShapeConfig);

            Assert.True(report.conforms);
        }

        private string rdfFile
        {
            get
            {
                StringBuilder rdfFile = new StringBuilder();
                rdfFile.Append("<rdf:RDF xmlns:bibo=\"http://purl.org/roh/mirror/bibo#\" xmlns:foaf=\"http://purl.org/roh/mirror/foaf#\" xmlns:obobfo=\"http://purl.org/roh/mirror/obo/bfo#\" xmlns:oboro=\"http://purl.org/roh/mirror/obo/ro#\" xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:roh=\"http://purl.org/roh#\" xmlns:rohes=\"http://purl.org/rohes#\" xmlns:vcard=\"http://purl.org/roh/mirror/vcard#\" xmlns:vivo=\"http://purl.org/roh/mirror/vivo#\">");
                rdfFile.Append("	<rdf:Description rdf:about=\"http://graph.um.es/res/person/1\">");
                rdfFile.Append("		<rdf:type rdf:resource = \"http://purl.org/roh/mirror/foaf#Person\" />");
                rdfFile.Append("		<roh:hasRole rdf:nodeID=\"N13102d9d82124e479f8d7042a8fab61a\" />");
                rdfFile.Append("		<foaf:phone rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">tel:666666666</foaf:phone>");
                rdfFile.Append("		<foaf:name rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Nombre Apellido</foaf:name>");
                rdfFile.Append("		<foaf:firstName rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Nombre</foaf:firstName>");
                rdfFile.Append("		<foaf:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Apellido</foaf:surname>");
                rdfFile.Append("		<vivo:identifier rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Identificador 1</vivo:identifier>");
                rdfFile.Append("	</rdf:Description>");
                rdfFile.Append("	<rdf:Description rdf:nodeID=\"N13102d9d82124e479f8d7042a8fab61a\">");
                rdfFile.Append("		<vivo:relates rdf:resource=\"http://graph.um.es/res/project/1\" />");
                rdfFile.Append("		<vivo:dateTimeInterval rdf:nodeID=\"N2552ff6c9f41464d85917e5286ac26d6\" />");
                rdfFile.Append("		<roh:roleOf rdf:resource=\"http://graph.um.es/res/person/1\" />");
                rdfFile.Append("		<rdf:type rdf:resource=\"http://purl.org/roh/mirror/vivo#MemberRole\" />");
                rdfFile.Append("	</rdf:Description>");
                rdfFile.Append("	<rdf:Description rdf:about=\"http://graph.um.es/res/project/1\">");
                rdfFile.Append("		<roh:title rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">IMPLICACIONES QUIMICAS Y BIOQUIMICAS EN EL COLOR Y AROMAS DEMOSTOS Y VINOS</roh:title>");
                rdfFile.Append("		<vivo:relatedBy rdf:nodeID=\"N92b3d38e204e40439f1ec47abd63b35e\" />");
                rdfFile.Append("		<rdf:type rdf:resource=\"http://purl.org/roh/mirror/vivo#Project\" />");
                rdfFile.Append("		<vivo:dateTimeInterval rdf:nodeID=\"Ncd7b021fabbd4f768a5c2f3869e85132\" />");
                rdfFile.Append("		<vivo:relates rdf:nodeID=\"N13102d9d82124e479f8d7042a8fab61a\" />");
                rdfFile.Append("		<roh:isSupportedBy rdf:nodeID=\"N0f320d4ca3184adb88ba7d1afdf624b1\" />");
                rdfFile.Append("	</rdf:Description>");
                rdfFile.Append("	<rdf:Description rdf:nodeID=\"N0f320d4ca3184adb88ba7d1afdf624b1\">");
                rdfFile.Append("		<roh:supports rdf:resource=\"http://graph.um.es/res/project/1\" />");
                rdfFile.Append("		<vivo:identifier rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">PCT89-4</vivo:identifier>");
                rdfFile.Append("		<rdf:type rdf:resource=\"http://purl.org/roh#Funding\" />");
                rdfFile.Append("		<oboro:BFO_0000051 rdf:nodeID=\"N5c0b27570e19415188b29776607abf7d\" />");
                rdfFile.Append("	</rdf:Description>");
                rdfFile.Append("	<rdf:Description rdf:nodeID=\"N5c0b27570e19415188b29776607abf7d\">");
                rdfFile.Append("		<oboro:BFO_0000050 rdf:nodeID=\"N0f320d4ca3184adb88ba7d1afdf624b1\" />");
                rdfFile.Append("		<rdf:type rdf:resource=\"http://purl.org/roh#FundingAmount\" />");
                rdfFile.Append("		<roh:monetaryAmount rdf:datatype=\"http://www.w3.org/2001/XMLSchema#decimal\">21035.42</roh:monetaryAmount>");
                rdfFile.Append("	</rdf:Description>");
                rdfFile.Append("	<rdf:Description rdf:nodeID=\"N2552ff6c9f41464d85917e5286ac26d6\">");
                rdfFile.Append("		<rdf:type rdf:resource=\"http://purl.org/roh/mirror/vivo#DateTimeInterval\" />");
                rdfFile.Append("		<vivo:start rdf:nodeID=\"N87c73ed5cf5e4d6d979fc46f2872d1fd\" />");
                rdfFile.Append("	</rdf:Description>");
                rdfFile.Append("	<rdf:Description rdf:nodeID=\"N87c73ed5cf5e4d6d979fc46f2872d1fd\">");
                rdfFile.Append("		<rdf:type rdf:resource=\"http://purl.org/roh/mirror/vivo#DateTimeValue\" />");
                rdfFile.Append("		<vivo:dateTime rdf:datatype=\"http://www.w3.org/2001/XMLSchema#dateTime\">1990-01-01T00:00:00.000+01:00</vivo:dateTime>");
                rdfFile.Append("	</rdf:Description>");
                rdfFile.Append("	<rdf:Description rdf:about=\"http://graph.um.es/res/project/1\">");
                rdfFile.Append("		<roh:title rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">IMPLICACIONES QUIMICAS Y BIOQUIMICAS EN EL COLOR Y AROMAS DEMOSTOS Y VINOS</roh:title>");
                rdfFile.Append("		<vivo:relatedBy rdf:nodeID=\"N92b3d38e204e40439f1ec47abd63b35e\" />");
                rdfFile.Append("		<rdf:type rdf:resource=\"http://purl.org/roh/mirror/vivo#Project\" />");
                rdfFile.Append("		<vivo:dateTimeInterval rdf:nodeID=\"Ncd7b021fabbd4f768a5c2f3869e85132\" />");
                rdfFile.Append("		<roh:isSupportedBy rdf:nodeID=\"N0f320d4ca3184adb88ba7d1afdf624b1\" />");
                rdfFile.Append("	</rdf:Description>");
                rdfFile.Append("	<rdf:Description rdf:nodeID=\"N92b3d38e204e40439f1ec47abd63b35e\">");
                rdfFile.Append("		<vivo:relates rdf:resource=\"http://graph.um.es/res/person/1\" />");
                rdfFile.Append("		<vivo:relates rdf:resource=\"http://graph.um.es/res/project/1\" />");
                rdfFile.Append("		<rdf:type rdf:resource=\"http://purl.org/roh/mirror/vivo#PrincipalInvestigatorRole\" />");
                rdfFile.Append("	</rdf:Description>");
                rdfFile.Append("	<rdf:Description rdf:nodeID=\"Ncd7b021fabbd4f768a5c2f3869e85132\">");
                rdfFile.Append("		<vivo:start rdf:nodeID=\"Na1caef70b2c54896a3a246a3c7033677\" />");
                rdfFile.Append("		<rdf:type rdf:resource=\"http://purl.org/roh/mirror/vivo#DateTimeInterval\" />");
                rdfFile.Append("	</rdf:Description>");
                rdfFile.Append("	<rdf:Description rdf:nodeID=\"Na1caef70b2c54896a3a246a3c7033677\">");
                rdfFile.Append("		<vivo:dateTime rdf:datatype=\"http://www.w3.org/2001/XMLSchema#dateTime\">1990-01-02T00:00:00.000+01:00</vivo:dateTime>");
                rdfFile.Append("		<rdf:type rdf:resource=\"http://purl.org/roh/mirror/vivo#DateTimeValue\" />");
                rdfFile.Append("	</rdf:Description>");
                rdfFile.Append("</rdf:RDF>");
                return rdfFile.ToString();
            }
        }

    }
}
