PREFIX roh: <http://purl.org/roh#>
PREFIX vivo: <http://purl.org/roh/mirror/vivo#>
PREFIX bibo:  <http://purl.org/roh/mirror/bibo#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?journal ?knowledgeArea 
WHERE {
?journalArticle vivo:hasPublicationVenue ?journal ;
bibo:authorList ?authorList ;
roh:hasMetric ?metric ;
roh:hasKnowledgeArea ?knowledgeArea .
?authorList ?member ?author .
?author roh:hasPosition ?position .
?position vivo:relates <http://purl.org/roh/data#centro-investigacion-1> .
?metric roh:quartile "Q2"^^<http://www.w3.org/2001/XMLSchema#string>}
