PREFIX roh: <http://purl.org/roh#>
PREFIX uneskos: <http://purl.org/roh/unesco-individuals#>

SELECT ?centro WHERE {
        ?centro a roh:ResearchGroup ;
                          roh:hasKnowledgeArea uneskos:120304 .
}