// <auto-generated />
using System;
using ApiPeliculas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiPeliculas.Migrations
{
    [DbContext(typeof(EntityContext))]
    [Migration("20210129090723_directorID")]
    partial class directorID
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ApiPeliculas.Models.Entities.Actor", b =>
                {
                    b.Property<Guid>("Actor_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Person_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Actor_ID");

                    b.ToTable("Actor");
                });

            modelBuilder.Entity("ApiPeliculas.Models.Entities.Director", b =>
                {
                    b.Property<Guid>("Director_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Person_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Director_ID");

                    b.ToTable("Director");
                });

            modelBuilder.Entity("ApiPeliculas.Models.Entities.Film", b =>
                {
                    b.Property<Guid>("Film_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Director_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MinuteRunTime")
                        .HasColumnType("int");

                    b.Property<string>("Released")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Film_ID");

                    b.HasIndex("Director_ID");

                    b.ToTable("Film");
                });

            modelBuilder.Entity("ApiPeliculas.Models.Entities.FilmActor", b =>
                {
                    b.Property<Guid>("Actor_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Film_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Actor_ID", "Film_ID");

                    b.HasIndex("Film_ID");

                    b.ToTable("FilmActor");
                });

            modelBuilder.Entity("ApiPeliculas.Models.Entities.Person", b =>
                {
                    b.Property<Guid>("Person_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Person_ID");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("ApiPeliculas.Models.Entities.Rating", b =>
                {
                    b.Property<Guid>("Rating_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Film_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Film_ID1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Rating_ID");

                    b.HasIndex("Film_ID1");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("ApiPeliculas.Models.Entities.Film", b =>
                {
                    b.HasOne("ApiPeliculas.Models.Entities.Director", "Director")
                        .WithMany("Films")
                        .HasForeignKey("Director_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("ApiPeliculas.Models.Entities.FilmActor", b =>
                {
                    b.HasOne("ApiPeliculas.Models.Entities.Actor", "Actor")
                        .WithMany("Films")
                        .HasForeignKey("Actor_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiPeliculas.Models.Entities.Film", "Film")
                        .WithMany("Actors")
                        .HasForeignKey("Film_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Film");
                });

            modelBuilder.Entity("ApiPeliculas.Models.Entities.Rating", b =>
                {
                    b.HasOne("ApiPeliculas.Models.Entities.Film", null)
                        .WithMany("Ratings")
                        .HasForeignKey("Film_ID1");
                });

            modelBuilder.Entity("ApiPeliculas.Models.Entities.Actor", b =>
                {
                    b.Navigation("Films");
                });

            modelBuilder.Entity("ApiPeliculas.Models.Entities.Director", b =>
                {
                    b.Navigation("Films");
                });

            modelBuilder.Entity("ApiPeliculas.Models.Entities.Film", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
