// <auto-generated />
using System;
using System.Collections.Generic;
using API_CARGA.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace API_CARGA.Migrations
{
    [DbContext(typeof(EntityContext))]
    [Migration("20200325100545_adSyncConfig")]
    partial class adSyncConfig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("API_CARGA.Models.Entities.RepositoryConfig", b =>
                {
                    b.Property<Guid>("RepositoryConfigID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OauthToken")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("RepositoryConfigID");

                    b.ToTable("RepositoryConfig");
                });

            modelBuilder.Entity("API_CARGA.Models.Entities.ShapeConfig", b =>
                {
                    b.Property<Guid>("ShapeConfigID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EntityClass")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Shape")
                        .HasColumnType("text");

                    b.HasKey("ShapeConfigID");

                    b.ToTable("ShapeConfig");
                });

            modelBuilder.Entity("API_CARGA.Models.Entities.SyncConfig", b =>
                {
                    b.Property<Guid>("SyncConfigID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RepositoryIdentifier")
                        .HasColumnType("uuid");

                    b.Property<List<string>>("RepositorySetIdentifiers")
                        .HasColumnType("text[]");

                    b.Property<string>("StartHour")
                        .HasColumnType("text");

                    b.Property<int>("UpdateFrequency")
                        .HasColumnType("integer");

                    b.HasKey("SyncConfigID");

                    b.ToTable("SyncConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
