// <auto-generated />
using System;
using System.Collections.Generic;
using API_CARGA.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace API_CARGA.Migrations
{
    [DbContext(typeof(EntityContext))]
    partial class EntityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("API_CARGA.Models.Entities.RepositoryConfig", b =>
                {
                    b.Property<Guid>("RepositoryConfigID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OauthToken")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("RepositoryConfigID");

                    b.ToTable("RepositoryConfig");
                });

            modelBuilder.Entity("API_CARGA.Models.Entities.RepositorySync", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Set")
                        .HasColumnType("text");

                    b.Property<DateTime>("UltimaFechaDeSincronizacion")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Sincronizacion_Repositorio");
                });

            modelBuilder.Entity("API_CARGA.Models.Entities.ShapeConfig", b =>
                {
                    b.Property<Guid>("ShapeConfigID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RepositoryID")
                        .HasColumnType("uuid");

                    b.Property<string>("Shape")
                        .HasColumnType("text");

                    b.HasKey("ShapeConfigID");

                    b.HasIndex("RepositoryID");

                    b.ToTable("ShapeConfig");
                });

            modelBuilder.Entity("API_CARGA.Models.Entities.SyncConfig", b =>
                {
                    b.Property<Guid>("SyncConfigID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RepositoryIdentifier")
                        .HasColumnType("uuid");

                    b.Property<List<string>>("RepositorySetIdentifiers")
                        .HasColumnType("text[]");

                    b.Property<string>("StartHour")
                        .HasColumnType("text");

                    b.Property<int>("UpdateFrequency")
                        .HasColumnType("integer");

                    b.HasKey("SyncConfigID");

                    b.ToTable("SyncConfig");
                });

            modelBuilder.Entity("API_CARGA.Models.Entities.ShapeConfig", b =>
                {
                    b.HasOne("API_CARGA.Models.Entities.RepositoryConfig", "RepositoryConfig")
                        .WithMany()
                        .HasForeignKey("RepositoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
