version: "3"
services:
    virtuoso:
        container_name:
            virtuoso
        image:
            openlink/virtuoso-opensource-7:latest
        environment:
            DBA_PASSWORD: mysecret      
            VIRTUOSO_INI_FILE:            
            VIRT_Parameters_NumberOfBuffers: 100000
            VIRT_Parameters_MaxDirtyBuffers: 60000
            VIRT_Parameters_MaxClientConnections: 100
            VIRT_HTTPServer_MaxClientConnections: 50
            VIRT_HTTPServer_ServerIdString: "virtuoso"
            VIRT_Zero Config_ServerName: "virtuoso"
            VIRT_I18N_XAnyNormalization: 3
        ports:
            - "1111:1111"
            - "8890:8890"
        volumes:
            - /var/container-data/virtuoso/db:/database   
        restart: always
