name: Build Hercules.Asio.SPARQLReplication

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build src/Hercules.Asio.SPARQLReplication
